[package]
name = "genericbot-rs"
version = "0.1.0"
authors = ["Ben Simms <ben@bensimms.moe>"]

[dependencies]
dotenv = "0.13.0"
chrono = "0.4.6"
typemap = "0.3.3"
r2d2 = "0.8.2"
base64 = "0.9.2"
regex = "1.0.4"
lazy_static = "1.1.0"
itertools = "0.7.8"
rand = "0.5.5"
procinfo = "0.4.2"
systemstat = "0.1.3"
whirlpool = "0.7.1"
reqwest = "0.8.8"
serde_json = "1.0.26"
lru-cache = "0.1.1"
threadpool = "1.7.1"
log = "0.4.4"
rmp-serde = "0.13.7"
serde = "1.0.75"
failure = "0.1.2"
fern = "0.5.6"

[dependencies.serenity]
git = "https://github.com/nitros12/serenity"
rev = "2ae4b71166b5e8b42425af086f0b9261e6549ea6"

[dependencies.diesel]
version = "1.3.2"
features = ["postgres", "chrono"]

[dependencies.r2d2-diesel]
git = "https://github.com/nitros12/r2d2-diesel"
