[package]
name = "genericbot-rs"
version = "0.1.0"
authors = ["Ben Simms <ben@bensimms.moe>"]

[dependencies]
serenity = { git = "https://github.com/nitros12/serenity", rev = "2cb9017e4dd2a697dde9233562a90459b0869cfb"}
diesel = { version = "1.2.2", features = ["postgres", "chrono"] }
dotenv = "0.11"
chrono = "0.4"
typemap = "0.3.3"
r2d2-diesel = "1.0.0"
r2d2 = "0.8.2"
base64 = "0.9"
regex = "0.2"
lazy_static = "1.0.0"
itertools = "0.7.8"
rand = "0.4.2"
procinfo = "0.4.2"
systemstat = "0.1.2"
whirlpool = "0.7.0"
reqwest = "0.8.5"
serde_json = "1.0"
log = "0.4.1"
lru-cache = "0.1.1"
threadpool = "1.7.1"
