[package]
name = "genericbot-rs"
version = "0.1.0"
authors = ["Ben Simms <ben@bensimms.moe>"]

[dependencies]
serenity = { git = "https://github.com/nitros12/serenity", rev = "b8f5c479074ec1bda2ee506b45303bc575b68e4b"}
diesel = { version = "1.3.0", features = ["postgres", "chrono"] }
dotenv = "0.12"
chrono = "0.4"
typemap = "0.3.3"
r2d2-diesel = { git = "https://github.com/nitros12/r2d2-diesel" }
r2d2 = "0.8.2"
base64 = "0.9"
regex = "1.0.0"
lazy_static = "1.0.0"
itertools = "0.7.8"
rand = "0.5.0"
procinfo = "0.4.2"
systemstat = "0.1.2"
whirlpool = "0.7.0"
reqwest = "0.8.5"
serde_json = "1.0.17"
lru-cache = "0.1.1"
threadpool = "1.7.1"
log = "0.4.1"
simplelog = "0.5.2"
rmp-serde = "0.13.7"
serde = "1.0.59"
