[package]
name = "genericbot-rs"
version = "0.1.0"
authors = ["Ben Simms <ben@bensimms.moe>"]

[dependencies]
serenity = { git = "https://github.com/nitros12/serenity", rev = "6f11a095dd78e22068d9c931da8f136eb9e2aa49"}
diesel = { version = "1.1.1", features = ["postgres"] }
dotenv = "0.11"
chrono = "0.4"
typemap = "0.3.3"
threadpool = "1.7.1"
r2d2-diesel = "1.0.0"
r2d2 = "0.8.2"
