[package]
name = "genericbot-rs"
version = "0.1.0"
authors = ["Ben Simms <ben@bensimms.moe>"]

[dependencies]
serenity = { git = "https://github.com/nitros12/serenity", rev = "79110d5698e4e432abfa38070a4bb3a6e4bb475f"}
diesel = { version = "1.3.2", features = ["postgres", "chrono"] }
dotenv = "0.13.0"
chrono = "0.4.4"
typemap = "0.3.3"
r2d2-diesel = { git = "https://github.com/nitros12/r2d2-diesel" }
r2d2 = "0.8.2"
base64 = "0.9.2"
regex = "1.0.1"
lazy_static = "1.0.1"
itertools = "0.7.8"
rand = "0.5.3"
procinfo = "0.4.2"
systemstat = "0.1.2"
whirlpool = "0.7.1"
reqwest = "0.8.6"
serde_json = "1.0.22"
lru-cache = "0.1.1"
threadpool = "1.7.1"
log = "0.4.3"
simplelog = "0.5.2"
rmp-serde = "0.13.7"
serde = "1.0.69"
failure = "0.1.1"
