[package]
name = "genericbot-rs"
version = "0.1.0"
authors = ["Ben Simms <ben@bensimms.moe>"]

[dependencies]
dotenv = "0.13.0"
chrono = "0.4.6"
typemap = "0.3.3"
r2d2 = "0.8.2"
base64 = "0.9.3"
regex = "1.0.5"
lazy_static = "1.1.0"
itertools = "0.7.8"
rand = "0.5.5"
procinfo = "0.4.2"
systemstat = "0.1.3"
whirlpool = "0.7.1"
reqwest = "0.9.1"
serde_json = "1.0.28"
lru-cache = "0.1.1"
threadpool = "1.7.1"
log = "0.4.5"
rmp-serde = "0.13.7"
serde = "1.0.79"
failure = "0.1.2"
fern = "0.5.6"

[dependencies.serenity]
# path = "../serenity"
git = "https://github.com/nitros12/serenity"
rev = "d350bf15d7cc57434a885255a508d0a3700577d9"

[dependencies.diesel]
version = "1.3.3"
features = ["postgres", "chrono", "r2d2"]

[patch.crates-io]
openssl = { git = "https://github.com/ishitatsuyuki/rust-openssl", branch = "0.9.x" }
